### ISSUE TITLE
`run*` does not work on python 3.8.10

### ISSUE THREAD

**Issue by kdvalin** [kdvalin/framebench#1]
```
Traceback (most recent call last):
  File "/root/venv/bin/framebench", line 8, in <module>
    sys.exit(main())
  File "/root/venv/lib/python3.8/site-packages/framebench/main.py", line 14, in main
    fire.Fire({
  File "/root/venv/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/venv/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/venv/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/venv/lib/python3.8/site-packages/framebench/run.py", line 21, in run
    test = CamTest(device, resolution, framerate, format, test_time)
  File "/root/venv/lib/python3.8/site-packages/framebench/test.py", line 20, in __init__
    self.vid = self._setup_capture_device()
  File "/root/venv/lib/python3.8/site-packages/framebench/test.py", line 67, in _setup_capture_device
    self.logger.info(f"Opened {self.cam} at {cv_resolution} {cv_fps}fps using {cv_format} encoding")
AttributeError: 'CamTest' object has no attribute 'logger'
```

**Comment by kdvalin** [comment]
Fixed in v1.0.2
